# Generated by Django 4.2.2 on 2023-07-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.CharField(choices=[('m', 'Medium'), ('s', 'Small'), ('x', 'Extra Small'), ('xl', 'Extra Large'), ('xxl', 'Extra Extra Large')], max_length=3, unique=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
