# Generated by Django 4.2.2 on 2023-07-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.CharField(choices=[('m', 'Medium'), ('s', 'Small'), ('x', 'Extra Small'), ('xl', 'Extra Large'), ('xxl', 'Extra Extra Large')], max_length=3),
        ),
    ]
